env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/recommended
  - plugin:functional/all

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: detect # https:stackoverflow.com/a/71436488

plugins:
  - react
  - "@typescript-eslint"
  - functional

rules:
  curly:
    - error
    - all

  # prettier
  indent: off
  linebreak-style: off
  quotes: off
  semi: off

  # 함수형 프로그래밍
  functional/prefer-readonly-type: warn
  functional/immutable-data: warn
  functional/no-expression-statement:
    - warn
    - ignoreVoid: true
  functional/functional-parameters: off
  functional/no-conditional-statement:
    - warn
    - allowReturningBranches: true

overrides:
  # 테스트 파일에서 vitest 관련 함수 허용
  - files: ["**/*.test.ts*"]
    rules:
      functional/no-expression-statement:
        - warn
        - ignoreVoid: true
          ignorePattern: [test, expect, to.*]

  # 스토리 파일에서 OBJ.args = { KEY: VALUE } 대입 허용
  - files: ["**/*.stories.ts*"]
    rules:
      functional/no-expression-statement:
        - warn
        - ignoreVoid: true
          ignorePattern: [args]

      functional/immutable-data:
        - warn
        - ignoreAccessorPattern: "**.args"
