env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/recommended
  - plugin:functional/all

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: detect # https:stackoverflow.com/a/71436488

plugins:
  - react
  - "@typescript-eslint"
  - functional
  - unused-imports

rules:
  object-shorthand:
    - error
    - always
  curly:
    - error
    - all
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"

  # prettier
  indent: off
  linebreak-style: off
  quotes: off
  semi: off
  max-lines: off

  # 함수형 프로그래밍
  functional/immutable-data: warn
  functional/prefer-readonly-type: off
  functional/functional-parameters: off
  functional/no-expression-statement: off # 현실적으로 불가능
  functional/no-conditional-statement:
    - warn
    - allowReturningBranches: true

  unused-imports/no-unused-imports: error

overrides:
  # 컴포넌트 타입은 리터럴과 함수를 모두 받아야 함
  - files: ["**/*.tsx", "**/*.test.ts*"]
    rules:
      functional/no-mixed-type: off

  # 스토리 파일에서 OBJ.args = { KEY: VALUE } 대입 허용
  - files: ["**/*.stories.ts*"]
    rules:
      functional/immutable-data:
        - warn
        - ignoreAccessorPattern: ["**.args", "**.argTypes"]
