name: 버그 리포트
description: 버-그
labels: ["버그"]

body:
  - type: checkboxes
    attributes:
      label: 해결 가능 여부
      description: 지금 해결 방법이 있는지 확인해주세요.
      options:
        - label: 지금 해결 가능

  - type: textarea
    attributes:
      label: 재현 방법
      description: 문제를 재현하기 위한 단계 (가능하다면 스크린샷 또는 영상도 추가해주세요)
      placeholder: |
        1. '...'로 이동
        2. '....'을 클릭
        3. '....'로 스크롤

  - type: input
    attributes:
      label: 노션 페이지
      description: 연결된 노션 페이지 주소를 입력해주세요.
      placeholder: notion.so
