name: CI/CD
description: CI/CD 파이프라인 관련 이슈
labels: ["CI/CD"]

body:
  - type: textarea
    attributes:
      label: 할 일
      description: 할 일에 대해 설명해주세요.
  - type: input
    attributes:
      label: 노션 페이지
      description: 연결된 노션 페이지 주소를 입력해주세요.
      placeholder: notion.so
