name: 기능 추가
description: 기능 추가, 변경
labels: ["기능 추가"]

body:
  - type: textarea
    attributes:
      label: 상세 설명
      description: 구현할 내용을 적어주세요.
      value: |
        - []

  - type: input
    attributes:
      label: 노션 페이지
      description: 연결된 노션 페이지 주소를 입력해주세요.
      placeholder: notion.so
