name: 코드 개선
description: 코드 리팩토링, 성능 개선
labels: ["코드 개선"]

body:
  - type: textarea
    attributes:
      label: 현재 상황
      description: 현재 개선이 필요한 코드 (개선이 필요한 부분, 이유 등..)

  - type: textarea
    attributes:
      label: 목표 상황
      description: 개선 시 기대되는 점

  - type: input
    attributes:
      label: 노션 페이지
      description: 연결된 노션 페이지 주소를 입력해주세요.
      placeholder: notion.so
