name: 할 일
description: 문서 작업, 문서 변경, 코드 단순 변경, 파일명 변경 등

body:
  - type: textarea
    attributes:
      label: 할 일
      description: 할 일에 대해 설명해주세요.

  - type: input
    attributes:
      label: 노션 페이지
      description: 연결된 노션 페이지 주소를 입력해주세요.
      placeholder: notion.so
