name: 프로젝트에 추가

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  add-to-project:
    name: 프로젝트에 추가하기
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/Team-Snacks/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT }}
